version: "3.2"

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    env_file:
      - ./backend/.env.dev
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app/frontend
      # One-way volume to use node_modules from inside image
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start

  db:
    image: postgres
    ports:
      - "8080:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env.dev

volumes:
  pgdata:


